// apps/web/src/app/components/input/input.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnInit,
  Output,
  QueryList,
  ViewChildren,
} from '@angular/core';

@Component({
  selector: 'app-input',
  standalone: true,
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.scss'],
})
export class InputComponent implements OnInit {
  @Input() value: string = '';
  @Input() className: string = '';
  @Input() style: { [klass: string]: any } = {};
  @Input() size: number = 10;
  @Input() type: 'text' | 'password' | 'number' | 'tel' = 'text';
  @Input() onlyNumber: boolean = false;

  @Output() valueChange = new EventEmitter<string>();

  arrayValue: string[] = [];

  @ViewChildren('inputRef') inputRefs!: QueryList<ElementRef<HTMLInputElement>>;

  ngOnInit(): void {
    if (this.value && this.value.length === this.size) {
      this.arrayValue = this.value.split('');
    } else {
      this.arrayValue = Array(this.size).fill('');
    }
  }

  numberMask(num: string): string {
    return num.replace(/\D/g, '');
  }

  handleInput(event: Event, i: number): void {
    const input = event.target as HTMLInputElement;
    if (!input.value) return;

    const prevChar = this.arrayValue[i];
    let char = '';

    if (this.onlyNumber) {
      const filtered = this.numberMask(input.value);
      if (filtered.length > 0) {
        char = filtered[filtered.length - 1];
      }
    } else {
      char = input.value[input.value.length - 1];
    }

    if (!char || char === prevChar) return;

    this.updateValue(char, i);

    // Move to next input
    if (i < this.size - 1) {
      this.inputRefs.get(i + 1)?.nativeElement.focus();
    }
  }

  handleKeyDown(event: KeyboardEvent, i: number): void {
    if (event.key === ' ') {
      event.preventDefault();
      this.updateValue(' ', i);
      if (i < this.size - 1) {
        this.inputRefs.get(i + 1)?.nativeElement.focus();
      }
    } else if (event.key === 'ArrowLeft' && i > 0) {
      this.inputRefs.get(i - 1)?.nativeElement.focus();
    } else if (event.key === 'ArrowRight' && i < this.size - 1) {
      this.inputRefs.get(i + 1)?.nativeElement.focus();
    } else if (event.key === 'Backspace') {
      event.preventDefault();
      if (this.arrayValue[i]) {
        // Case 1: Current box has a character, just clear it
        this.updateValue('', i);
        // Keep focus in current
        this.inputRefs.get(i)?.nativeElement.focus();
      } else if (i > 0) {
        // Case 2: Current is empty, move left and clear previous
        this.updateValue('', i - 1);
        this.inputRefs.get(i - 1)?.nativeElement.focus();
      }
    } else if (event.key === 'Delete') {
      event.preventDefault();
      this.updateValue('', i);
    }
  }

  updateValue(char: string, index: number): void {
    const result = [...this.arrayValue];

    if (char === '') {
      result[index] = '';
    } else {
      // If current slot is empty, just write the char without shifting
      if (result[index] === '') {
        result[index] = char;
      } else {
        // Shift right only if current slot is occupied
        for (let j = this.size - 1; j > index; j--) {
          result[j] = result[j - 1];
        }
        result[index] = char;
      }
    }

    this.arrayValue = result;
    this.emitChange();
  }

  emitChange(): void {
    this.valueChange.emit(this.arrayValue.join(''));
  }
}

<div
  class="input-group {{ className }}"
  [style]="style"
>
@for (val of arrayValue; track $index; let i = $index) {
  <div
    class="input-container"
  >
    <input
      #inputRef
      class="input-box"
      [type]="type"
      [value]="val"
      (input)="handleInput($event, i)"
      (keydown)="handleKeyDown($event, i)"
    />
  </div>
}
</div>

// apps/web/src/components/input/input.tsx
import React, {
  useEffect,
  useRef,
  useState,
  type CSSProperties,
  type RefObject,
} from "react";
import "./input.css";

const numberMask = (num: string): string => num.replace(/\D/g, "");

interface InputProps {
  value: string;
  className?: string;
  style?: CSSProperties;
  size?: number;
  type?: "text" | "password" | "number" | "tel";
  isConfirmInput?: boolean;
  onlyNumber?: boolean;
  onChange: (value: string) => void;
}

export default function InputBox({
  value,
  className,
  style,
  size = 10,
  type = "text",
  onlyNumber = false,
  onChange,
}: InputProps) {
  const [arrayValue, setArrayValue] = useState<string[]>([]);
  const refs = useRef<React.RefObject<HTMLInputElement>[]>([]);

  // Ensure refs only initialized once
  if (refs.current.length !== size) {
    refs.current = Array(size)
      .fill(null)
      .map(
        () => React.createRef<HTMLInputElement>() as RefObject<HTMLInputElement>
      );
  }

  useEffect(() => {
    // Initialize only once
    if (arrayValue.length === 0) {
      if (value && value.length === size) {
        setArrayValue(value.split(""));
      } else {
        setArrayValue(Array(size).fill(""));
      }
    }
  }, [arrayValue.length, value, size]);

  const handleKeyDown = (
    e: React.KeyboardEvent<HTMLInputElement>,
    i: number
  ) => {
    if (e.key === " ") {
      e.preventDefault();
      handleChange(" ", i);
      if (i < size - 1) {
        refs.current[i + 1]?.current?.focus();
      }
    } else if (e.key === "ArrowLeft" && i > 0) {
      refs.current[i - 1]?.current?.focus();
    } else if (e.key === "ArrowRight" && i < size - 1) {
      refs.current[i + 1]?.current?.focus();
    } else if (e.key === "Backspace") {
      e.preventDefault();

      setArrayValue((prev) => {
        const result = [...prev];

        // Shift left from i+1 to end
        for (let j = i; j < size - 1; j++) {
          result[j] = result[j + 1];
        }
        // Clear last item
        result[size - 1] = "";

        // Call onChange in effect (see below)
        return result;
      });

      // Move focus logically
      if (i > 0) {
        refs.current[i - 1]?.current?.focus();
      } else {
        refs.current[i]?.current?.focus();
      }
    } else if (e.key === "Delete") {
      e.preventDefault();
      handleChange("", i);
    }
  };

  const handleChange = (char: string, index: number) => {
    setArrayValue((prev) => {
      const result = [...prev];
      if (char === "") {
        result[index] = "";
      } else {
        for (let j = size - 1; j > index; j--) {
          result[j] = result[j - 1];
        }
        result[index] = char;
      }
      return result;
    });
  };
  useEffect(() => {
    onChange(arrayValue.join(""));
  }, [arrayValue, onChange]);

  const handleInput = (e: React.ChangeEvent<HTMLInputElement>, i: number) => {
    const inputVal = e.currentTarget.value;
    if (!inputVal) return;

    const prevChar = arrayValue[i];
    let char = "";

    if (onlyNumber) {
      const filtered = numberMask(inputVal);
      if (filtered.length > 0) {
        char = filtered[filtered.length - 1];
      }
    } else {
      char = inputVal[inputVal.length - 1];
    }

    if (!char || char === prevChar) return;

    handleChange(char, i);

    // Move focus to next input if any
    if (i < size - 1) {
      refs.current[i + 1]?.current?.focus();
    }
  };

  return (
    <div className={`${className ?? ""} input-group`} style={style}>
      {arrayValue.map((val, i) => (
        <div key={i} className="input-container">
          <input
            className="input-box"
            type={type}
            value={val ?? ""}
            ref={refs.current[i]}
            onChange={(e) => handleInput(e, i)}
            onKeyDown={(e) => handleKeyDown(e, i)}
          />
        </div>
      ))}
    </div>
  );
}
